### ISSUE TITLE
exist an error in function “void cSolver::compute_disagreement()”

### ISSUE THREAD

**Issue by chenxianbo** [MegviiRobot/OdomLaserCalibraTool#1]
void cSolver::compute_disagreement(cSynchronizer::sync_data &calib_data, const calib_result &res)
{
.........
  if (fabs(o_theta) > 1e-12)
  {
    t1 = sin(o_theta) / o_theta;
    t2 = (1 - cos(o_theta)) / o_theta;
  }
  else
  {
    t1 = 0;
    t2 = 0;
  }
.......
}

when "fabs(o_theta) < 1e-12", the t1 should equal to  one

**Comment by paulwong16** [comment]
> void cSolver::compute_disagreement(cSynchronizer::sync_data &calib_data, const calib_result &res)
> {
> .........
> if (fabs(o_theta) > 1e-12)
> {
> t1 = sin(o_theta) / o_theta;
> t2 = (1 - cos(o_theta)) / o_theta;
> }
> else
> {
> t1 = 0;
> t2 = 0;
> }
> .......
> }
> 
> when "fabs(o_theta) < 1e-12", the t1 should equal to one

t1 is sinc(o_theta), and as you commented, it should be 1 when fabs(o_theta) < 1e-12.

Thanks for contribution and we have fixed it.
