### ISSUE TITLE
计算雷达里程计 部分的代码是不是存在错误？

### ISSUE THREAD

**Issue by hitxiaomi** [MegviiRobot/OdomLaserCalibraTool#11]
感谢开源这么棒的工作！
 

想问下 计算雷达里程计 部分的代码是不是存在错误？

https://github.com/MegviiRobot/OdomLaserCalibraTool/blob/5de1ec7a329c27c7e0162eecf922d6c07dfdda86/src/scan_match.cpp#L139-L140

result  中应该保存的是相对 位置变化，应该对应与 注释中的  {b_x, b_y_, b_theta} 部分吧？

**Comment by vzhr** [comment]
我也感觉是这个。你有确认这个的正确性吗？
