### ISSUE TITLE
What information of topic 'odom' is actullay utilized?

### ISSUE THREAD

**Issue by Miaowaaaa** [MegviiRobot/OdomLaserCalibraTool#3]
I note that the code in [io.cpp#L72](https://github.com/MegviiRobot/OdomLaserCalibraTool/blob/5de1ec7a329c27c7e0162eecf922d6c07dfdda86/src/io.cpp#L72) reads the position information of the robot. But in [Readme](https://github.com/MegviiRobot/OdomLaserCalibraTool/edit/master/README.md#L22), the veloctiy of left and right wheels is required. So I confuse that what information is input indeed?

**Comment by HeYijia** [comment]
If you use Odom (x,y,yaw) data, you can replace the code [ io.cpp: line72-line79](https://github.com/MegviiRobot/OdomLaserCalibraTool/blob/5de1ec7a329c27c7e0162eecf922d6c07dfdda86/src/io.cpp#L72) to [line 49-line61].  We support different types of rostopic.

**Comment by Miaowaaaa** [comment]
> If you use Odom (x,y,yaw) data, you can replace the code [ io.cpp: line72-line79](https://github.com/MegviiRobot/OdomLaserCalibraTool/blob/5de1ec7a329c27c7e0162eecf922d6c07dfdda86/src/io.cpp#L72) to [line 49-line61]. We support different types of rostopic.

Does it mean that the radius of left & right wheels and the distance between the wheels should be given?

**Comment by HeYijia** [comment]
You can use these parameters we give. It doesn't matter you use the actual radius of wheels or use the virtual parameters we give.

**Comment by paulwong16** [comment]
> > If you use Odom (x,y,yaw) data, you can replace the code [ io.cpp: line72-line79](https://github.com/MegviiRobot/OdomLaserCalibraTool/blob/5de1ec7a329c27c7e0162eecf922d6c07dfdda86/src/io.cpp#L72) to [line 49-line61]. We support different types of rostopic.
> 
> Does it mean that the radius of left & right wheels and the distance between the wheels should be given?

It depends on what parameters you need to calibrate. If you want to calibrate the intrinsic parameters of odometer, then you need the real radius and the track of wheels, otherwise, you can use the virtual one since it will not affect the calibration results of extrinsic parameters. I suggest you can read the paper carefully then you can understand the code better.
