### ISSUE TITLE
The wheel radius in the calibration parameters is negative

### ISSUE THREAD

**Issue by Cristalyoyo** [MegviiRobot/OdomLaserCalibraTool#6]
Hi, I encountered the following problems while using the program
The absolute value of the calibration result is basically consistent with the actual parameters of the robot, but the wheel radius and laser-odom x are negative.
The attachment has data and a more detailed problem description.

[datas_and_questions.zip](https://github.com/MegviiRobot/OdomLaserCalibraTool/files/4715647/datas_and_questions.zip)

**Comment by paulwong16** [comment]
> Hi, I encountered the following problems while using the program
> The absolute value of the calibration result is basically consistent with the actual parameters of the robot, but the wheel radius and laser-odom x are negative.
> The attachment has data and a more detailed problem description.
> 
> [datas_and_questions.zip](https://github.com/MegviiRobot/OdomLaserCalibraTool/files/4715647/datas_and_questions.zip)

Please check if wheels' velocity are correct. odom->vector.x should be left wheel's velocity and vector.y should be the right, respectively, otherwise please modify the code in line 76&77 in io.cpp.

Best,
Zhijie

**Comment by Cristalyoyo** [comment]
> > Hi, I encountered the following problems while using the program
> > The absolute value of the calibration result is basically consistent with the actual parameters of the robot, but the wheel radius and laser-odom x are negative.
> > The attachment has data and a more detailed problem description.
> > [datas_and_questions.zip](https://github.com/MegviiRobot/OdomLaserCalibraTool/files/4715647/datas_and_questions.zip)
> 
> Please check if wheels' velocity are correct. odom->vector.x should be left wheel's velocity and vector.y should be the right, respectively, otherwise please modify the code in line 76&77 in io.cpp.
> 
> Best,
> Zhijie

Thank you for your support and help, the problem has been solved～～
Best wishes,
Lihong
