### ISSUE TITLE
Suitable for wheel odom and 3D laser(velodyne)?

### ISSUE THREAD

**Issue by narutojxl** [MegviiRobot/OdomLaserCalibraTool#7]
Hi doctor he,
Thanks for your work !
We can use this project to calibrate the extrinsic between a wheel odom and a velodyne-16, or there is some reference paper about this? Thanks very much !
Best

**Comment by paulwong16** [comment]
> Hi doctor he,
> 
> Thanks for your work !
> 
> We can use this project to calibrate the extrinsic between a wheel odom and a velodyne-16, or there is some reference paper about this? Thanks very much !
> 
> Best

Hi,

I believe you cannot use this software on 3D LiDAR directly, since 3D matching is different you might need to rewrite the objective function in optimization problem, and not sure if it still has a closed-form solution (but you can solve it numerically 

Best,
Zhijie

**Comment by narutojxl** [comment]
@paulwong16, thanks for your detailed reply and suggestion.

Best
